name: Publish

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        description: 'npm tag to publish to'
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  publish_snapshot:
    name: Publish
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: true # needed for git push

      - uses: ./.github/composites/setup

      # see https://github.com/actions/checkout/tree/main#push-a-commit-using-the-built-in-token
      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: git tag
        run: |
          bash -c "jq -r '\"v\" + .version' package.json | xargs -I '{}' git tag -a '{}' -m '{}'"

      - run: pnpm build
      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: npm publish
        run: pnpm publish --access=public --tag ${{ inputs.npm_tag }} --recursive --report-summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: git push
        run: git push origin --tags
