name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/composites/setup
      - run: pnpm build

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/composites/setup
      - run: pnpm test:types

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # see https://nodejs.org/en/about/releases/
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@main
      - uses: ./.github/composites/setup
      - run: pnpm test:unit
